version: 2.1
orbs:
  go: circleci/go@1.7.1
jobs:
  build:
    executor:
      name: go/default
      tag: "1.19"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: |
            touch .env
            echo ${{ GO_ENV }} >> .env
            cat .env
      - run:
          name: Run tests
          command: go test -v ./cmd/web