version: 2.1
orbs:
  go: circleci/go@1.7.2
jobs:
  build:
    executor:
      name: go/default
      tag: "1.19"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run:
            name: Decode dotenv file
            command: echo $GO_ENV | base64 --decode > .env
      - run:
          name: Run tests
          command: go test -v ./cmd/web