version: 2.1
orbs:
  go: circleci/go@1.7.1
jobs:
  build:
    executor:
      name: go/default
      tag: "1.19"
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - checkout
        - run:
          name: Setup custom environment variables
          command: echo '${GO_ENV}' >> .env
        - run:
          name: What branch am I on?
          command: echo ${GO_ENV}
        - run:
          name: What branch am I on now?
          command: echo $GO_ENV
        - run:
          name: What was my custom environment variable?
          command: echo ${GO_ENV}
        - run:
          name: Print an env var stored in the Project
          command: echo ${GO_ENV}
        - run:
          name: Print an env var stored in a Context
          command: echo ${GO_ENV}
      - run:
          name: Run tests
          command: go test -v ./cmd/web